[bok]
authors = ["Magnus Madsen"]
language = "en"
multilingual = false
src = "src"
title = "Programming Flix"

[output.html]
git-repository-url = "https://github.com/flix/book/"
edit-url-template = "https://github.com/flix/book/edit/master/{path}"
